version: '3.1'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./logs/php/:/var/log/
    entrypoint: [ "/bin/sh", "-c", "php artisan migrate && docker-php-entrypoint php-fpm"]
  postgres:
    image: postgres:14
    ports: 
      - "5432:5432"
    networks:
      - internal
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
    restart: always
networks:
  internal:
    driver: bridge